### ISSUE TITLE
Updating malli dependencies

### ISSUE THREAD

**Issue by josephwinston** [teknql/wing#1]
I wanted to use https://github.com/teknql/wing/blob/master/src/wing/malli/json.cljc but is using an obsolete malli API.

Here are the notes from Malli's CHANGELOG 

m/map-entries is removed, m/entries returns a MapEntry of key & m/-val-schema

Any chance that you have a branch in place that uses a new version of malli?

**Comment by rschmukler** [comment]
Hey! Thanks for bringing this up, and checking out the repo. I'll update to the latest version of malli ASAP.

**Comment by josephwinston** [comment]
Thank you so much.  I’m just learning malli and your repository has been a great example.

**Comment by rschmukler** [comment]
@josephwinston republished under `0.0.1-SNAPSHOT` with the latest changes. Thanks again!
